unit TestMenuUnit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, AdaptersUnit, MenuUnit, System.Generics.Collections, MainUnit,
  AccessAdapterUnit;

type
  // Test methods for class Menu

  TestMenu = class(TTestCase)
  strict private
    FMenu: Menu;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestMenu.SetUp;
begin
  FMenu := Menu.Create;
end;

procedure TestMenu.TearDown;
begin
  FMenu.Free;
  FMenu := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestMenu.Suite);
end.

